---
title: "Learning Resources"
subtitle: Furthering Your Knowledge of R & R Markdown
output:
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Follow R Conversation on Twitter

### R Power Users

**Suscribe To My R-Tweets List**: I created a Twitter List of people who tweet really relevant stuff about R. It's not perfect by any means and could probably be better if I had more time to keep up with it, but it's a decent list of interesting R Power Tweeters. 

### R Hashtags To Follow

A lot of how I've learned R is by discovering the [#rstats](https://twitter.com/hashtag/rstats?src=hash) hashtag on twitter. From everything I've seen, that hashtag feels like the best way to see what's new or developing in the world of R. I saved it as a search on twitter, and see what people are discussing at least once every day. Sounds crazy, but a quick glance through the top tweets will let you discover new stuff you didn't know R was capable or see what's been updated for a package or tool you use regularly.

Other hashtags I have saved which help me keep track of packages or areas of usage within the world of R are #rspatial (for GIS stuff), [#rmarkdown](https://twitter.com/hashtag/rmarkdown?src=hash), [#blogdown](https://twitter.com/hashtag/blogdown?src=hash), [#bookdown](https://twitter.com/hashtag/bookdown?src=hash), [#tidycensus](https://twitter.com/hashtag/tidycensus?src=hash), and [#tidyverse](https://twitter.com/hashtag/tidyverse?src=hash). 


## Lynda.com Courses on R

Lynda.com is a paid resource, but is provided free for UT Students with a UT EID username & password. When you sign in, make sure to select `Sign In With Your Organization Portal` and, when prompted, type "utexas.edu" for the domain. Once you hit enter, you'll be asked to sign in with your UT EID. Alternatively, clicking on one of the courses below will prompt you to sign in with your UT EID username and password. After signing in, you'll be able to access course materials that guide you through that course.

  * [**"Learning R": **](https://www.lynda.com/R-tutorials/Up-Running-R/120612-2.html?org=utexas.edu) The course continues with examples on how to create charts and plots, check statistical assumptions and the reliability of your data, look for data outliers, and use other data analysis tools. Finally, learn how to get charts and tables out of R and share your results with presentations and web pages. (Course Description from Lynda.com)
  * [**"Learning The R Tidyverse": **](https://www.lynda.com/R-tutorials/Learning-R-Tidyverse/586672-2.html?org=utexas.edu) R is an incredibly powerful and widely used programming language for statistical analysis and data science. The "tidyverse" collects some of the most versatile R packages: ggplot2, dplyr, tidyr, readr, purrr, and tibble. The packages work in harmony to clean, process, model, and visualize data. This course introduces the core concepts of the tidyverse as compared to the traditional base R. It focuses on the novice user and those unfamiliar with the pipe (%>%) operator. After covering these R basics, instructor Martin Hadley progresses to importing and filtering data from Excel, CSV, and SPSS files, and summarizing and tabulating data in the tidyverse. Then learn how to identify if data is too wide or long and convert it if necessary, and conduct nonstandard evaluation. By the end of the course, you should be able to integrate the tidyverse into your R workflow and leverage a variety of new tools for importing, filtering, visualizing, and modeling research and statistical data. (Course Description from Lynda.com)
  * [**"R Statistics Essential Training": **](https://www.lynda.com/R-tutorials/R-Statistics-Essential-Training/142447-2.html?org=utexas.edu) R is the language of big data—a statistical programming language that helps describe, mine, and test relationships between large amounts of data. Author Barton Poulson shows how to use R to model statistical relationships using graphs, calculations, tests, and other analysis tools. Learn how to enter and modify data; create charts, scatter plots, and histograms; examine outliers; calculate correlations; and compute regressions, bivariate associations, and statistics for three or more variables. (Course Description from Lynda.com)
  * [**"R: Interactive Visualizations with htmlwidgets": **](https://www.lynda.com/R-tutorials/R-Interactive-Visualizations-htmlwidgets/586671-2.html?org=utexas.edu) Using the R language almost exclusively, htmlwidgets allow you to create the same interactive maps, charts, and graphs you see on popular data journalism sites and in BI dashboards. You can connect R to popular JavaScript libraries—such as Plotly and Leaflet—with htmlwidget packages. The interactive visualizations you create can be used in R Markdown reports and presentations, and even integrated into rich, responsive Shiny applications. This course introduces you to the fundamental skills needed to add htmlwidgets to your R workflow. (Course Description from Lynda.com)

## DataCamp Courses

DataCamp is an incredible, but paid resource. Before you complain about the latter, consider that the people making these courses are often the same people who have developed various R Packages that are completely free to use. 

While some professors at UT who utilize DataCamp in their classes are able to provide enrolled students with free licenses for that semester, it is not free to any university student. That said, if you're not one of those lucky university students whose professor uses it, you can take advantage of some of their free content or keep an eye out for discounted promotions they offer. Typically, they're promoted around big holidays and have steep discounts.

  * [**"Reporting with R Markdown": **](https://www.datacamp.com/courses/reporting-with-r-markdown) Learn how to write a data report quickly and effectively with the R Markdown package, and share your results with your friends, colleagues or the rest of the world. Learn how you can author your own R Markdown reports, and how to automate the reporting process so that you have your own reproducible reports. By the end of the interactive data analysis reporting tutorial, you will be able to generate reports straight from your R code, documenting your work — and its results — as an HTML, pdf, slideshow or Microsoft Word document. (Course Description from Lynda.com)
  * [**"Other R DataCamp Courses": **](https://www.datacamp.com/courses/tech:r) This is a link to a pretty extensive list of R-specific courses that DataCamp has available. 
